language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - virtualenv .
  - source bin/activate
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
before_script:

script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coveralls
  - bin/coveralls
notifications:
  email:
    - bauer@starzel.de
